---
label: flexpart_ifs
description: ""
default_calc_job_plugin: flexpart.ifs
computer: daint
filepath_executable: /users/lfernand/flexpart_ifs_empa/bin/FLEXPART91IFS_omp
prepend_text: |

    export OMP_STACKSIZE=100M
    module load daint-mc
    module switch PrgEnv-cray PrgEnv-gnu
    module switch gcc/11.2.0 gcc/9.3.0

    module load cray-netcdf
    module use /store/empa/em05/shenne/easybuild/modules/all
    module load ecCodes/2.19.0-CrayGNU-21.09

append_text: ""
