---
* username               yaa
* port                   22
* look_for_keys          True
* key_filename
* timeout                60
* allow_agent            True
* proxy_jump             yaa@ela.cscs.ch
* proxy_command
* compress               True
* gss_auth               False
* gss_kex                False
* gss_deleg_creds        False
* gss_host               daint
* load_system_host_keys  True
* key_policy             RejectPolicy
* use_login_shell        True
* safe_interval          30.0
